spring:
  application:
    name: books_jdbc
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console